#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudLinq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Clientes")]
	public partial class ConexionClienteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConexionClienteDataContext() : 
				base(global::CrudLinq.Properties.Settings.Default.ClientesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionClienteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionClienteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionClienteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionClienteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarCliente")]
		public int ActualizarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apePaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apeMaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string telefono)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombre, apePaterno, apeMaterno, telefono);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarCliente")]
		public ISingleResult<BuscarClienteResult> BuscarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<BuscarClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarCliente")]
		public int EliminarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCliente")]
		public int InsertarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apePaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apeMaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string telefono)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apePaterno, apeMaterno, telefono);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarCliente")]
		public ISingleResult<ListarClienteResult> ListarCliente()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarClienteResult>)(result.ReturnValue));
		}
	}
	
	public partial class BuscarClienteResult
	{
		
		private int _idCli;
		
		private string _nombreCli;
		
		private string _apellidoPaternoCli;
		
		private string _apellidoMaternoCli;
		
		private string _telefonoCli;
		
		public BuscarClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCli", DbType="Int NOT NULL")]
		public int idCli
		{
			get
			{
				return this._idCli;
			}
			set
			{
				if ((this._idCli != value))
				{
					this._idCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCli", DbType="VarChar(50)")]
		public string nombreCli
		{
			get
			{
				return this._nombreCli;
			}
			set
			{
				if ((this._nombreCli != value))
				{
					this._nombreCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoPaternoCli", DbType="VarChar(50)")]
		public string apellidoPaternoCli
		{
			get
			{
				return this._apellidoPaternoCli;
			}
			set
			{
				if ((this._apellidoPaternoCli != value))
				{
					this._apellidoPaternoCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoMaternoCli", DbType="VarChar(50)")]
		public string apellidoMaternoCli
		{
			get
			{
				return this._apellidoMaternoCli;
			}
			set
			{
				if ((this._apellidoMaternoCli != value))
				{
					this._apellidoMaternoCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefonoCli", DbType="VarChar(50)")]
		public string telefonoCli
		{
			get
			{
				return this._telefonoCli;
			}
			set
			{
				if ((this._telefonoCli != value))
				{
					this._telefonoCli = value;
				}
			}
		}
	}
	
	public partial class ListarClienteResult
	{
		
		private int _idCli;
		
		private string _nombreCli;
		
		private string _apellidoPaternoCli;
		
		private string _apellidoMaternoCli;
		
		private string _telefonoCli;
		
		public ListarClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCli", DbType="Int NOT NULL")]
		public int idCli
		{
			get
			{
				return this._idCli;
			}
			set
			{
				if ((this._idCli != value))
				{
					this._idCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCli", DbType="VarChar(50)")]
		public string nombreCli
		{
			get
			{
				return this._nombreCli;
			}
			set
			{
				if ((this._nombreCli != value))
				{
					this._nombreCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoPaternoCli", DbType="VarChar(50)")]
		public string apellidoPaternoCli
		{
			get
			{
				return this._apellidoPaternoCli;
			}
			set
			{
				if ((this._apellidoPaternoCli != value))
				{
					this._apellidoPaternoCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoMaternoCli", DbType="VarChar(50)")]
		public string apellidoMaternoCli
		{
			get
			{
				return this._apellidoMaternoCli;
			}
			set
			{
				if ((this._apellidoMaternoCli != value))
				{
					this._apellidoMaternoCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefonoCli", DbType="VarChar(50)")]
		public string telefonoCli
		{
			get
			{
				return this._telefonoCli;
			}
			set
			{
				if ((this._telefonoCli != value))
				{
					this._telefonoCli = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
